import { CalendarRange, Sparkles } from "lucide-react";
import type { IncidentType, Severity } from "@/generated/prisma/enums";
import { SeverityBadge } from "@/components/severity-badge";
import { INCIDENT_TYPE_LABELS } from "@/lib/constants";
import { formatDate } from "@/lib/format";

/**
 * The weekly digests this village has already had, on `/reports`.
 *
 * `GET|POST /api/digest` has written one `PatternAlert` per active village per
 * run since Day 6 and **nothing has ever rendered one** — a standing entry in
 * "Not built yet". This is the reading half of that: the summaries in the order
 * they were written, so a coordinator preparing for a parish meeting can read
 * back over the quarter rather than reconstructing it from the incident list.
 *
 * **Read-only, deliberately.** `acknowledgedAt` and `dismissedAt` are columns
 * with no UI and this does not add one: acknowledging an alert is a decision
 * with a write behind it, and it wants its own thinking rather than a button
 * added in passing to a list that is otherwise inert.
 *
 * ## Which summaries were written by a model, and which were counted
 *
 * `detector` carries it. The digest falls back to `weekly-count` when Claude is
 * unavailable — no key, a rate limit, a timeout — and produces a summary
 * assembled from the counts instead of nothing, because inventing prose to fill
 * the gap would make an outage look like a working digest.
 *
 * That distinction is surfaced rather than smoothed over, for the reason
 * `GENERATED_BY` is conditional on the narrative's source in everything
 * `/reports` produces: a reader deciding how much of a document to trust is
 * entitled to know which of the two they are holding. `confidence` is not
 * rendered — it is a detector's own score for its own clustering, and a
 * percentage beside a paragraph would read as how sure the summary is.
 */

/** The detector a counted fallback records, rather than a model's analysis. */
const COUNTED_DETECTOR = "weekly-count";

export type WeeklySummary = {
  id: string;
  title: string;
  summary: string;
  type: IncidentType | null;
  severity: Severity;
  incidentCount: number;
  /** ISO strings — the window the digest covered. */
  windowStart: string;
  windowEnd: string;
  detector: string;
  createdAt: string;
};

export function WeeklySummaryHistory({
  summaries,
}: {
  summaries: readonly WeeklySummary[];
}) {
  return (
    <section className="mt-6" data-print-hide>
      <h2 className="flex items-center gap-2 text-lg font-semibold text-slate-900">
        <CalendarRange className="size-5 text-slate-400" aria-hidden />
        Weekly summaries
      </h2>
      <p className="mt-1 text-sm text-slate-500">
        Written automatically every Sunday from the reports your village
        published that week. Nothing here is sent to anyone — it is a record you
        can read back over.
      </p>

      {summaries.length === 0 ? (
        <p className="mt-4 rounded-2xl border border-slate-200 bg-white p-4 text-sm leading-relaxed text-slate-500 sm:p-5">
          No weekly summary has been written yet. The first one arrives after
          your village has published reports and the Sunday digest has run.
        </p>
      ) : (
        <ol className="mt-4 space-y-3">
          {summaries.map((summary) => {
            const counted = summary.detector === COUNTED_DETECTOR;

            return (
              <li
                key={summary.id}
                className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"
              >
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div className="min-w-0">
                    <h3 className="text-sm font-semibold text-slate-900">
                      {summary.title}
                    </h3>
                    <p className="mt-0.5 text-xs text-slate-500">
                      {formatDate(summary.windowStart)} –{" "}
                      {formatDate(summary.windowEnd)} · {summary.incidentCount}{" "}
                      report{summary.incidentCount === 1 ? "" : "s"}
                      {summary.type && (
                        <> · mostly {INCIDENT_TYPE_LABELS[summary.type]}</>
                      )}
                    </p>
                  </div>
                  <SeverityBadge severity={summary.severity} />
                </div>

                <p className="mt-3 whitespace-pre-line text-sm leading-relaxed text-slate-700">
                  {summary.summary}
                </p>

                {/*
                  Only where a model wrote it. The same rule the report footer
                  follows: printing "generated by AI" over a paragraph that is a
                  count invites a reader to discount the count.
                */}
                {counted ? (
                  <p className="mt-3 text-xs text-slate-400">
                    Counted from your village’s reports. No analysis was
                    available that week.
                  </p>
                ) : (
                  <p className="mt-3 flex items-center gap-1.5 text-xs text-slate-400">
                    <Sparkles className="size-3.5 shrink-0" aria-hidden />
                    Written by VillageWatch AI from the week’s published reports.
                  </p>
                )}
              </li>
            );
          })}
        </ol>
      )}
    </section>
  );
}
