import { describe, expect, it } from "vitest";
import {
  formatCommunityReport,
  formatIncidentSummary,
  reportController,
  type CommunityReportData,
  type ReportIncident,
  type ReportNarrative,
} from "@/lib/community-report";
import { APP_NAME, DATA_CONTROLLER } from "@/lib/constants";

/**
 * The line a recipient reads to decide how much of the document to trust.
 *
 * Both documents `community-report.ts` produces close with the same block, and
 * its first sentence used to read "Generated by VillageWatch AI" on every one of
 * them — including a period report whose only prose is `countedNarrative`, which
 * is a paragraph assembled from `SELECT count(*)`, and the single-incident
 * summary, which has no analysis section at all. A police officer discounting
 * arithmetic because the footer told them a model wrote it is a worse outcome
 * than a plainer sentence.
 *
 * So the claim is now conditional on `narrative.source`, which already carried
 * the distinction for the paragraph on screen. This asserts the condition in
 * both directions on both documents, because the footer is shared and a fix
 * applied to one call site is the failure mode.
 *
 * Client-safe module — no Prisma, no secret, no environment. `appUrl` is passed
 * explicitly so the assertions do not depend on `NEXT_PUBLIC_APP_URL`.
 */

const APP_URL = "https://villagewatch.example";

/** The sentence that may only appear over prose a model actually wrote. */
const AI_CLAIM = "The pattern analysis in it was written by AI.";

const INCIDENT: ReportIncident = {
  id: "inc-1",
  reference: "VW-HIS-2026-0003",
  type: "VEHICLE_CRIME",
  severity: "MEDIUM",
  title: "Car window smashed on Mill Lane",
  description: "A vehicle window was broken overnight near the recreation ground.",
  locationText: "Mill Lane",
  occurredAt: new Date("2026-08-03T22:10:00Z"),
  reportedAt: new Date("2026-08-04T07:40:00Z"),
  recurring: false,
  patternNote: null,
  anonymized: true,
};

function narrative(source: ReportNarrative["source"]): ReportNarrative {
  return {
    summary: "Four reports, three of them overnight on the same stretch of road.",
    patterns: ["Three of the four vehicle reports were overnight on Mill Lane."],
    recommendation: null,
    source,
    model: source === "ai" ? "claude-sonnet-5" : null,
  };
}

function report(
  narrativeValue: ReportNarrative | null,
): CommunityReportData {
  return {
    villageName: "Histon",
    dataController: "Histon Neighbourhood Watch",
    from: new Date("2026-08-01T00:00:00Z"),
    to: new Date("2026-08-31T23:59:59Z"),
    generatedAt: new Date("2026-09-01T09:00:00Z"),
    total: 1,
    previousTotal: 0,
    byType: [{ key: "VEHICLE_CRIME", count: 1 }],
    bySeverity: [{ key: "MEDIUM", count: 1 }],
    hotspots: [{ location: "Mill Lane", count: 1 }],
    // Empty for the same reason `police` is: the footer's AI claim is about the
    // narrative and nothing else, and a fixture carrying a section this test
    // does not assert would be asserting one sentence through a longer
    // document.
    mostConcerning: [],
    // The footer's AI claim is about the narrative and nothing else, so the
    // police comparison is deliberately absent here — a fixture that carried
    // one would be asserting the same sentence through a longer document.
    police: null,
    narrative: narrativeValue,
    incidents: [INCIDENT],
    omitted: 0,
  };
}

describe("the period report's footer", () => {
  it("claims AI only where a model wrote the analysis", () => {
    const written = formatCommunityReport(report(narrative("ai")), APP_URL);

    expect(written).toContain(`Generated by ${APP_NAME}.`);
    expect(written).toContain(AI_CLAIM);
  });

  it("makes no AI claim over a counted narrative", () => {
    // The regression this exists for. `countedNarrative` is arithmetic, and it
    // is what every report falls back to when Anthropic is unreachable or the
    // coordinator never pressed the button — which is the ordinary case for a
    // downloaded PDF, where `?analysis=ai` is opt-in.
    const counted = formatCommunityReport(report(narrative("counted")), APP_URL);

    expect(counted).toContain(`Generated by ${APP_NAME}.`);
    expect(counted).not.toContain(AI_CLAIM);
  });

  it("makes no AI claim when no analysis was generated at all", () => {
    const bare = formatCommunityReport(report(null), APP_URL);

    expect(bare).not.toContain(AI_CLAIM);
  });

  it("still says who the data controller is, either way", () => {
    // The other half of the footer is unconditional: it is the only thing
    // telling a recipient outside the village who to take a UK GDPR complaint
    // to, and it does not depend on whether a model wrote a paragraph.
    for (const source of ["ai", "counted"] as const) {
      expect(formatCommunityReport(report(narrative(source)), APP_URL)).toContain(
        "Data controller: Histon Neighbourhood Watch.",
      );
    }
  });
});

describe("the single-incident summary's footer", () => {
  it("never claims AI, because the document has no analysis in it", () => {
    // This one has no narrative to be conditional on: it is a formatting of one
    // report a coordinator is already looking at. The `description` it quotes
    // was rewritten by a model, and that is said in the sentence below the
    // claim rather than in it.
    const summary = formatIncidentSummary(
      {
        incident: INCIDENT,
        villageName: "Histon",
        dataController: "Histon Neighbourhood Watch",
      },
      APP_URL,
    );

    expect(summary).toContain(`Generated by ${APP_NAME}.`);
    expect(summary).not.toContain(AI_CLAIM);
    expect(summary).toContain("Descriptions are anonymised before publication");
  });
});

describe("reportController", () => {
  it("falls back to the deployment constant, which names no council", () => {
    // The placeholder is mode-neutral now: `Village.mode` defaults to
    // `community`, where there is no council, so a fallback reading
    // "[Parish Council name]" asked most villages for something that does not
    // exist. It is still visibly a placeholder — `/reports` warns on exactly
    // this value — it just no longer describes the wrong kind of village.
    expect(reportController(null)).toBe(DATA_CONTROLLER.name);
    expect(reportController("   ")).toBe(DATA_CONTROLLER.name);
    expect(DATA_CONTROLLER.name).not.toMatch(/council/i);
  });

  it("prefers the village's own name, trimmed", () => {
    expect(reportController("  Bourn Parish Council  ")).toBe(
      "Bourn Parish Council",
    );
  });
});
